/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kbc;

import javax.swing.JOptionPane;

/**
 *
 * @author Sanidhya Singh
 */
public class Q4 extends javax.swing.JFrame {

    /**
     * Creates new form Q4
     */
    public Q4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        kButton4 = new com.k33ptoo.components.KButton();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton3 = new com.k33ptoo.components.KButton();
        kButton1 = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(607, 300));
        getContentPane().setLayout(null);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(102, 153, 255));
        jTextField1.setFont(new java.awt.Font("Open Sans Semibold", 1, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(242, 242, 242));
        jTextField1.setText("In terms of of production, which of these is the largest train coach manufacturing unit in thr world?");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(90, 80, 873, 40);

        kButton4.setText("Integeral Coach Factory, Banglore");
        kButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kButton4.setkBorderRadius(40);
        kButton4.setkEndColor(new java.awt.Color(51, 102, 255));
        kButton4.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        kButton4.setkHoverForeGround(new java.awt.Color(242, 242, 242));
        kButton4.setkStartColor(new java.awt.Color(102, 0, 204));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(kButton4);
        kButton4.setBounds(150, 170, 280, 45);

        kButton2.setText("Integral Coach Factory, Mumbai");
        kButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kButton2.setkBorderRadius(40);
        kButton2.setkEndColor(new java.awt.Color(51, 102, 255));
        kButton2.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        kButton2.setkHoverForeGround(new java.awt.Color(242, 242, 242));
        kButton2.setkStartColor(new java.awt.Color(102, 0, 204));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(kButton2);
        kButton2.setBounds(600, 170, 270, 45);

        kButton3.setText("Integeral Coach Factory, Chennai");
        kButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kButton3.setkBorderRadius(40);
        kButton3.setkEndColor(new java.awt.Color(51, 102, 255));
        kButton3.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        kButton3.setkHoverForeGround(new java.awt.Color(242, 242, 242));
        kButton3.setkStartColor(new java.awt.Color(102, 0, 204));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(kButton3);
        kButton3.setBounds(150, 280, 280, 45);

        kButton1.setText("Integeral Coach Factory, Kolkata");
        kButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kButton1.setkBorderRadius(40);
        kButton1.setkEndColor(new java.awt.Color(51, 102, 255));
        kButton1.setkHoverEndColor(new java.awt.Color(0, 204, 204));
        kButton1.setkHoverForeGround(new java.awt.Color(242, 242, 242));
        kButton1.setkStartColor(new java.awt.Color(102, 0, 204));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(kButton1);
        kButton1.setBounds(600, 280, 270, 45);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kbc1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1024, 448);

        setSize(new java.awt.Dimension(1014, 448));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        JOptionPane.showMessageDialog(null,"Try Again!");
        Home h=new Home();
        h.show();
        dispose();
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
       Q5 w=new Q5();
       w.show();
       dispose();
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        JOptionPane.showMessageDialog(null,"Try Again!");
        Home h=new Home();
        h.show();
        dispose();
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        JOptionPane.showMessageDialog(null,"Try Again!");
        Home h=new Home();
        h.show();
        dispose();
    }//GEN-LAST:event_kButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Q4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Q4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Q4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Q4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Q4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KButton kButton3;
    private com.k33ptoo.components.KButton kButton4;
    // End of variables declaration//GEN-END:variables
}
